macaddress:
  - "00:14:ee:03:96:45"
  - "00:14:ee:03:96:46"
authorized_keys:
  - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINCPCeqDxLSZz/1BVTQu62dU+D+mowjZc3aNE1HGbnUo"
hostname: "nas"
username: "quaak"
password: "Admin1234"

ubuntu_version: "21.04"
ubuntu_iso: "ubuntu-{{ubuntu_version}}-live-server-amd64.iso"
ubuntu_iso_checksum: "sha256:e4089c47104375b59951bad6c7b3ee5d9f6d80bfac4597e43a716bb8f5c1f3b0"

packer_image_name: "nas-ubuntu-server.qcow2"
packer_image_name_raw: "nas-ubuntu-server.img"
